### ISSUE TITLE
v1.0 issues

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-solar#1]
Well we did it again: no RGB LED. I'm. So. Disappointed. In. Us.

Also: add an output power LED. Silly, but for debugging, it would be informative. It'd show us if the SPV1040 is working (or not). 

Obviously, all LEDs are NP on the gold boards.

# TODO:

Add the following:

 - [ ] RGB LED
 - [ ] Power LED
 - [x] Silkscreen board number area
 - [x] `!SHUTDOWN` line blocking diode
 - [ ] Fiducials
 - [ ] Decide what to do with the through-hole version of the Harting connector: add the holes, or just keep cutting off the leads to make it SMD assuming that part isn't available?
 - [x] Should add Vsolar to the debug breakout so you can power the whole module off that connector.
 - [x] BOOT0 (pin 31) on the STM32 needs to be pulled to ground (also, a test point).

**Comment by andrewgreenberg** [comment]
Need a large silkscreen area for writing the board number on the board (on both sides)

**Comment by andrewgreenberg** [comment]
OreSat !SHUTDOWN line needs a good blocking diode. Probably a full silicon diode, one with very little reverse leakage at high temperatures.

**Comment by andrewgreenberg** [comment]
Duh: need fiducials if we send these out.

**Comment by natronics** [comment]
Updated issue body with formatted checklist of sub-items.
